# Generated by Django 5.0.3 on 2024-04-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_service_backend', '0006_alter_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbehavior',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
