# Generated by Django 5.0.3 on 2024-06-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_service_backend', '0007_alter_userbehavior_is_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
